/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/C_Cpp/README': RouteRecordInfo<
      '/posts/myNotes/C_Cpp/README',
      '/posts/myNotes/C_Cpp/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/C_Cpp/stl_unordered_map': RouteRecordInfo<
      '/posts/myNotes/C_Cpp/stl_unordered_map',
      '/posts/myNotes/C_Cpp/stl_unordered_map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/C_Cpp/virtual': RouteRecordInfo<
      '/posts/myNotes/C_Cpp/virtual',
      '/posts/myNotes/C_Cpp/virtual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/基于 Linux Input 子系统的 FT5426 触摸屏驱动开发复盘': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/基于 Linux Input 子系统的 FT5426 触摸屏驱动开发复盘',
      '/posts/myNotes/embedded-linux/%E5%9F%BA%E4%BA%8E%20Linux%20Input%20%E5%AD%90%E7%B3%BB%E7%BB%9F%E7%9A%84%20FT5426%20%E8%A7%A6%E6%91%B8%E5%B1%8F%E9%A9%B1%E5%8A%A8%E5%BC%80%E5%8F%91%E5%A4%8D%E7%9B%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/基于 Xilinx DRM 显示管线的 ATK LCD 驱动与背光集成复盘': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/基于 Xilinx DRM 显示管线的 ATK LCD 驱动与背光集成复盘',
      '/posts/myNotes/embedded-linux/%E5%9F%BA%E4%BA%8E%20Xilinx%20DRM%20%E6%98%BE%E7%A4%BA%E7%AE%A1%E7%BA%BF%E7%9A%84%20ATK%20LCD%20%E9%A9%B1%E5%8A%A8%E4%B8%8E%E8%83%8C%E5%85%89%E9%9B%86%E6%88%90%E5%A4%8D%E7%9B%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/concurrency&competition': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/concurrency&competition',
      '/posts/myNotes/embedded-linux/concurrency&competition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/debug': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/debug',
      '/posts/myNotes/embedded-linux/debug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/device_Identification': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/device_Identification',
      '/posts/myNotes/embedded-linux/device_Identification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/drivers_overview': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/drivers_overview',
      '/posts/myNotes/embedded-linux/drivers_overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/drm_xilinx': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/drm_xilinx',
      '/posts/myNotes/embedded-linux/drm_xilinx',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/dts_overview': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/dts_overview',
      '/posts/myNotes/embedded-linux/dts_overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/header_overview': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/header_overview',
      '/posts/myNotes/embedded-linux/header_overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/i2c': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/i2c',
      '/posts/myNotes/embedded-linux/i2c',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/i2c_core': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/i2c_core',
      '/posts/myNotes/embedded-linux/i2c_core',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/i2c_input_touchscreen': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/i2c_input_touchscreen',
      '/posts/myNotes/embedded-linux/i2c_input_touchscreen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/i2c_msg': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/i2c_msg',
      '/posts/myNotes/embedded-linux/i2c_msg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/input': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/input',
      '/posts/myNotes/embedded-linux/input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/Interrupt': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/Interrupt',
      '/posts/myNotes/embedded-linux/Interrupt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/kernel_boot_process': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/kernel_boot_process',
      '/posts/myNotes/embedded-linux/kernel_boot_process',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/embedded-linux/scheduler': RouteRecordInfo<
      '/posts/myNotes/embedded-linux/scheduler',
      '/posts/myNotes/embedded-linux/scheduler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/复制ChatGPT回复为Markdown格式': RouteRecordInfo<
      '/posts/myNotes/guide/复制ChatGPT回复为Markdown格式',
      '/posts/myNotes/guide/%E5%A4%8D%E5%88%B6ChatGPT%E5%9B%9E%E5%A4%8D%E4%B8%BAMarkdown%E6%A0%BC%E5%BC%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/部署千问': RouteRecordInfo<
      '/posts/myNotes/guide/部署千问',
      '/posts/myNotes/guide/%E9%83%A8%E7%BD%B2%E5%8D%83%E9%97%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/antigravity-proxy': RouteRecordInfo<
      '/posts/myNotes/guide/antigravity-proxy',
      '/posts/myNotes/guide/antigravity-proxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/chrome-in-podman': RouteRecordInfo<
      '/posts/myNotes/guide/chrome-in-podman',
      '/posts/myNotes/guide/chrome-in-podman',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/ghostty-appimage-fcitx5': RouteRecordInfo<
      '/posts/myNotes/guide/ghostty-appimage-fcitx5',
      '/posts/myNotes/guide/ghostty-appimage-fcitx5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/HAProxy-WG-Proxy': RouteRecordInfo<
      '/posts/myNotes/guide/HAProxy-WG-Proxy',
      '/posts/myNotes/guide/HAProxy-WG-Proxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/how_to_setup_proxy': RouteRecordInfo<
      '/posts/myNotes/guide/how_to_setup_proxy',
      '/posts/myNotes/guide/how_to_setup_proxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/Install_Cuda_and_pytorch_in_WSL': RouteRecordInfo<
      '/posts/myNotes/guide/Install_Cuda_and_pytorch_in_WSL',
      '/posts/myNotes/guide/Install_Cuda_and_pytorch_in_WSL',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/install_vivado_in_wsl': RouteRecordInfo<
      '/posts/myNotes/guide/install_vivado_in_wsl',
      '/posts/myNotes/guide/install_vivado_in_wsl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/install_windows_in_kvm': RouteRecordInfo<
      '/posts/myNotes/guide/install_windows_in_kvm',
      '/posts/myNotes/guide/install_windows_in_kvm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/Linux玩游戏': RouteRecordInfo<
      '/posts/myNotes/guide/Linux玩游戏',
      '/posts/myNotes/guide/Linux%E7%8E%A9%E6%B8%B8%E6%88%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/Manually_booting_the_Linux_kernel_from_GRUB': RouteRecordInfo<
      '/posts/myNotes/guide/Manually_booting_the_Linux_kernel_from_GRUB',
      '/posts/myNotes/guide/Manually_booting_the_Linux_kernel_from_GRUB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/nfs': RouteRecordInfo<
      '/posts/myNotes/guide/nfs',
      '/posts/myNotes/guide/nfs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/OBS与FFmpeg参数设置': RouteRecordInfo<
      '/posts/myNotes/guide/OBS与FFmpeg参数设置',
      '/posts/myNotes/guide/OBS%E4%B8%8EFFmpeg%E5%8F%82%E6%95%B0%E8%AE%BE%E7%BD%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/optimize_bash': RouteRecordInfo<
      '/posts/myNotes/guide/optimize_bash',
      '/posts/myNotes/guide/optimize_bash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/Optimizing_PowerShell': RouteRecordInfo<
      '/posts/myNotes/guide/Optimizing_PowerShell',
      '/posts/myNotes/guide/Optimizing_PowerShell',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/repair-linux-grub': RouteRecordInfo<
      '/posts/myNotes/guide/repair-linux-grub',
      '/posts/myNotes/guide/repair-linux-grub',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/run_linux_in_qemu': RouteRecordInfo<
      '/posts/myNotes/guide/run_linux_in_qemu',
      '/posts/myNotes/guide/run_linux_in_qemu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/scripts': RouteRecordInfo<
      '/posts/myNotes/guide/scripts',
      '/posts/myNotes/guide/scripts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/Solve_the_problem_of_CMake_printing_a_lot_of_included_information_when_building_with_MSVC': RouteRecordInfo<
      '/posts/myNotes/guide/Solve_the_problem_of_CMake_printing_a_lot_of_included_information_when_building_with_MSVC',
      '/posts/myNotes/guide/Solve_the_problem_of_CMake_printing_a_lot_of_included_information_when_building_with_MSVC',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/unix-like_shell_in_windows': RouteRecordInfo<
      '/posts/myNotes/guide/unix-like_shell_in_windows',
      '/posts/myNotes/guide/unix-like_shell_in_windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/use-git-in-vscode': RouteRecordInfo<
      '/posts/myNotes/guide/use-git-in-vscode',
      '/posts/myNotes/guide/use-git-in-vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/vivado_error_[Vivado_12-8300]': RouteRecordInfo<
      '/posts/myNotes/guide/vivado_error_[Vivado_12-8300]',
      '/posts/myNotes/guide/vivado_error_:Vivado_12-8300',
      { Vivado_12-8300: ParamValue<true> },
      { Vivado_12-8300: ParamValue<false> },
      | never
    >,
    '/posts/myNotes/guide/vscode_clangd': RouteRecordInfo<
      '/posts/myNotes/guide/vscode_clangd',
      '/posts/myNotes/guide/vscode_clangd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/guide/zsh': RouteRecordInfo<
      '/posts/myNotes/guide/zsh',
      '/posts/myNotes/guide/zsh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/mcu/Port-freertos-to-gd32': RouteRecordInfo<
      '/posts/myNotes/mcu/Port-freertos-to-gd32',
      '/posts/myNotes/mcu/Port-freertos-to-gd32',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/nuttx/nsh_run_app_process': RouteRecordInfo<
      '/posts/myNotes/nuttx/nsh_run_app_process',
      '/posts/myNotes/nuttx/nsh_run_app_process',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/nuttx/nx_start': RouteRecordInfo<
      '/posts/myNotes/nuttx/nx_start',
      '/posts/myNotes/nuttx/nx_start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/nuttx/On-Demand-Paging_reserch': RouteRecordInfo<
      '/posts/myNotes/nuttx/On-Demand-Paging_reserch',
      '/posts/myNotes/nuttx/On-Demand-Paging_reserch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/nuttx/On-Demand-Paging_zh-CN': RouteRecordInfo<
      '/posts/myNotes/nuttx/On-Demand-Paging_zh-CN',
      '/posts/myNotes/nuttx/On-Demand-Paging_zh-CN',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/': RouteRecordInfo<
      '/posts/myNotes/path2offer/',
      '/posts/myNotes/path2offer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/实习-nuttx-信号量': RouteRecordInfo<
      '/posts/myNotes/path2offer/实习-nuttx-信号量',
      '/posts/myNotes/path2offer/%E5%AE%9E%E4%B9%A0-nuttx-%E4%BF%A1%E5%8F%B7%E9%87%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/实习-nuttx-aio': RouteRecordInfo<
      '/posts/myNotes/path2offer/实习-nuttx-aio',
      '/posts/myNotes/path2offer/%E5%AE%9E%E4%B9%A0-nuttx-aio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/bytedance_server_firmware': RouteRecordInfo<
      '/posts/myNotes/path2offer/bytedance_server_firmware',
      '/posts/myNotes/path2offer/bytedance_server_firmware',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/c_io': RouteRecordInfo<
      '/posts/myNotes/path2offer/c_io',
      '/posts/myNotes/path2offer/c_io',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/interview_exp': RouteRecordInfo<
      '/posts/myNotes/path2offer/interview_exp',
      '/posts/myNotes/path2offer/interview_exp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/linux_kernel': RouteRecordInfo<
      '/posts/myNotes/path2offer/linux_kernel',
      '/posts/myNotes/path2offer/linux_kernel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/mcu': RouteRecordInfo<
      '/posts/myNotes/path2offer/mcu',
      '/posts/myNotes/path2offer/mcu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/mcu_ldscript': RouteRecordInfo<
      '/posts/myNotes/path2offer/mcu_ldscript',
      '/posts/myNotes/path2offer/mcu_ldscript',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/mcu_startup': RouteRecordInfo<
      '/posts/myNotes/path2offer/mcu_startup',
      '/posts/myNotes/path2offer/mcu_startup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/path2offer/os_memory': RouteRecordInfo<
      '/posts/myNotes/path2offer/os_memory',
      '/posts/myNotes/path2offer/os_memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/arrival-vector': RouteRecordInfo<
      '/posts/myNotes/radar/arrival-vector',
      '/posts/myNotes/radar/arrival-vector',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/Capon-algorithm': RouteRecordInfo<
      '/posts/myNotes/radar/Capon-algorithm',
      '/posts/myNotes/radar/Capon-algorithm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/Compare_Capon_and_PhaseDiff_algorithm_in_1T2R_Radar': RouteRecordInfo<
      '/posts/myNotes/radar/Compare_Capon_and_PhaseDiff_algorithm_in_1T2R_Radar',
      '/posts/myNotes/radar/Compare_Capon_and_PhaseDiff_algorithm_in_1T2R_Radar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/Data_Association-Global_Nearest_Neighbor': RouteRecordInfo<
      '/posts/myNotes/radar/Data_Association-Global_Nearest_Neighbor',
      '/posts/myNotes/radar/Data_Association-Global_Nearest_Neighbor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/FFT_frequency_interpolation': RouteRecordInfo<
      '/posts/myNotes/radar/FFT_frequency_interpolation',
      '/posts/myNotes/radar/FFT_frequency_interpolation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/LFMCW-radar-principle': RouteRecordInfo<
      '/posts/myNotes/radar/LFMCW-radar-principle',
      '/posts/myNotes/radar/LFMCW-radar-principle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/MUSIC-algorithm': RouteRecordInfo<
      '/posts/myNotes/radar/MUSIC-algorithm',
      '/posts/myNotes/radar/MUSIC-algorithm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection': RouteRecordInfo<
      '/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection',
      '/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation': RouteRecordInfo<
      '/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation',
      '/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/README': RouteRecordInfo<
      '/posts/myNotes/README',
      '/posts/myNotes/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/resource': RouteRecordInfo<
      '/posts/myNotes/resource',
      '/posts/myNotes/resource',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/some-details/compare_numpy_arange_and_linspace': RouteRecordInfo<
      '/posts/myNotes/some-details/compare_numpy_arange_and_linspace',
      '/posts/myNotes/some-details/compare_numpy_arange_and_linspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/some-details/gist_url': RouteRecordInfo<
      '/posts/myNotes/some-details/gist_url',
      '/posts/myNotes/some-details/gist_url',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/some-details/list_find_in_vscode': RouteRecordInfo<
      '/posts/myNotes/some-details/list_find_in_vscode',
      '/posts/myNotes/some-details/list_find_in_vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/some-details/the-format-of-the-Passtags-of-the-ZMQ-module-in-GNURadio': RouteRecordInfo<
      '/posts/myNotes/some-details/the-format-of-the-Passtags-of-the-ZMQ-module-in-GNURadio',
      '/posts/myNotes/some-details/the-format-of-the-Passtags-of-the-ZMQ-module-in-GNURadio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/some-details/transpose-in-matlab': RouteRecordInfo<
      '/posts/myNotes/some-details/transpose-in-matlab',
      '/posts/myNotes/some-details/transpose-in-matlab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp': RouteRecordInfo<
      '/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp',
      '/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/tools/Python_scripts_modify_the_encoding_format_of_text_files_in_batches': RouteRecordInfo<
      '/posts/myNotes/tools/Python_scripts_modify_the_encoding_format_of_text_files_in_batches',
      '/posts/myNotes/tools/Python_scripts_modify_the_encoding_format_of_text_files_in_batches',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/zynq/add_lrzsz_in_rootfs': RouteRecordInfo<
      '/posts/myNotes/zynq/add_lrzsz_in_rootfs',
      '/posts/myNotes/zynq/add_lrzsz_in_rootfs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/myNotes/zynq/Petalinux_design_process': RouteRecordInfo<
      '/posts/myNotes/zynq/Petalinux_design_process',
      '/posts/myNotes/zynq/Petalinux_design_process',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.10_magicast@0.5.3_vue@3.5.35_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.10_@babel+parser@7.29.7_@nuxt+kit@3.21.7_magicast@0.5.3__@types+markdown-it_04db7d62b53a218c672f1aba232324c1/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.10_magicast@0.5.3_vue@3.5.35_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/C_Cpp/README.md': {
      routes:
        | '/posts/myNotes/C_Cpp/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/C_Cpp/stl_unordered_map.md': {
      routes:
        | '/posts/myNotes/C_Cpp/stl_unordered_map'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/C_Cpp/virtual.md': {
      routes:
        | '/posts/myNotes/C_Cpp/virtual'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/基于 Linux Input 子系统的 FT5426 触摸屏驱动开发复盘.md': {
      routes:
        | '/posts/myNotes/embedded-linux/基于 Linux Input 子系统的 FT5426 触摸屏驱动开发复盘'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/基于 Xilinx DRM 显示管线的 ATK LCD 驱动与背光集成复盘.md': {
      routes:
        | '/posts/myNotes/embedded-linux/基于 Xilinx DRM 显示管线的 ATK LCD 驱动与背光集成复盘'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/concurrency&competition.md': {
      routes:
        | '/posts/myNotes/embedded-linux/concurrency&competition'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/debug.md': {
      routes:
        | '/posts/myNotes/embedded-linux/debug'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/device_Identification.md': {
      routes:
        | '/posts/myNotes/embedded-linux/device_Identification'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/drivers_overview.md': {
      routes:
        | '/posts/myNotes/embedded-linux/drivers_overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/drm_xilinx.md': {
      routes:
        | '/posts/myNotes/embedded-linux/drm_xilinx'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/dts_overview.md': {
      routes:
        | '/posts/myNotes/embedded-linux/dts_overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/header_overview.md': {
      routes:
        | '/posts/myNotes/embedded-linux/header_overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/i2c.md': {
      routes:
        | '/posts/myNotes/embedded-linux/i2c'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/i2c_core.md': {
      routes:
        | '/posts/myNotes/embedded-linux/i2c_core'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/i2c_input_touchscreen.md': {
      routes:
        | '/posts/myNotes/embedded-linux/i2c_input_touchscreen'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/i2c_msg.md': {
      routes:
        | '/posts/myNotes/embedded-linux/i2c_msg'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/input.md': {
      routes:
        | '/posts/myNotes/embedded-linux/input'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/Interrupt.md': {
      routes:
        | '/posts/myNotes/embedded-linux/Interrupt'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/kernel_boot_process.md': {
      routes:
        | '/posts/myNotes/embedded-linux/kernel_boot_process'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/embedded-linux/scheduler.md': {
      routes:
        | '/posts/myNotes/embedded-linux/scheduler'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/复制ChatGPT回复为Markdown格式.md': {
      routes:
        | '/posts/myNotes/guide/复制ChatGPT回复为Markdown格式'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/部署千问.md': {
      routes:
        | '/posts/myNotes/guide/部署千问'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/antigravity-proxy.md': {
      routes:
        | '/posts/myNotes/guide/antigravity-proxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/chrome-in-podman.md': {
      routes:
        | '/posts/myNotes/guide/chrome-in-podman'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/ghostty-appimage-fcitx5.md': {
      routes:
        | '/posts/myNotes/guide/ghostty-appimage-fcitx5'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/HAProxy-WG-Proxy.md': {
      routes:
        | '/posts/myNotes/guide/HAProxy-WG-Proxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/how_to_setup_proxy.md': {
      routes:
        | '/posts/myNotes/guide/how_to_setup_proxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/Install_Cuda_and_pytorch_in_WSL.md': {
      routes:
        | '/posts/myNotes/guide/Install_Cuda_and_pytorch_in_WSL'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/install_vivado_in_wsl.md': {
      routes:
        | '/posts/myNotes/guide/install_vivado_in_wsl'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/install_windows_in_kvm.md': {
      routes:
        | '/posts/myNotes/guide/install_windows_in_kvm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/Linux玩游戏.md': {
      routes:
        | '/posts/myNotes/guide/Linux玩游戏'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/Manually_booting_the_Linux_kernel_from_GRUB.md': {
      routes:
        | '/posts/myNotes/guide/Manually_booting_the_Linux_kernel_from_GRUB'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/nfs.md': {
      routes:
        | '/posts/myNotes/guide/nfs'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/OBS与FFmpeg参数设置.md': {
      routes:
        | '/posts/myNotes/guide/OBS与FFmpeg参数设置'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/optimize_bash.md': {
      routes:
        | '/posts/myNotes/guide/optimize_bash'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/Optimizing_PowerShell.md': {
      routes:
        | '/posts/myNotes/guide/Optimizing_PowerShell'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/repair-linux-grub.md': {
      routes:
        | '/posts/myNotes/guide/repair-linux-grub'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/run_linux_in_qemu.md': {
      routes:
        | '/posts/myNotes/guide/run_linux_in_qemu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/scripts.md': {
      routes:
        | '/posts/myNotes/guide/scripts'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/Solve_the_problem_of_CMake_printing_a_lot_of_included_information_when_building_with_MSVC.md': {
      routes:
        | '/posts/myNotes/guide/Solve_the_problem_of_CMake_printing_a_lot_of_included_information_when_building_with_MSVC'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/unix-like_shell_in_windows.md': {
      routes:
        | '/posts/myNotes/guide/unix-like_shell_in_windows'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/use-git-in-vscode.md': {
      routes:
        | '/posts/myNotes/guide/use-git-in-vscode'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/vivado_error_[Vivado_12-8300].md': {
      routes:
        | '/posts/myNotes/guide/vivado_error_[Vivado_12-8300]'
      views:
        | never
      pathParamNames:
        | 'Vivado_12-8300'
    }
    'pages/posts/myNotes/guide/vscode_clangd.md': {
      routes:
        | '/posts/myNotes/guide/vscode_clangd'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/guide/zsh.md': {
      routes:
        | '/posts/myNotes/guide/zsh'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/mcu/Port-freertos-to-gd32.md': {
      routes:
        | '/posts/myNotes/mcu/Port-freertos-to-gd32'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/nuttx/nsh_run_app_process.md': {
      routes:
        | '/posts/myNotes/nuttx/nsh_run_app_process'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/nuttx/nx_start.md': {
      routes:
        | '/posts/myNotes/nuttx/nx_start'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/nuttx/On-Demand-Paging_reserch.md': {
      routes:
        | '/posts/myNotes/nuttx/On-Demand-Paging_reserch'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/nuttx/On-Demand-Paging_zh-CN.md': {
      routes:
        | '/posts/myNotes/nuttx/On-Demand-Paging_zh-CN'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/index.md': {
      routes:
        | '/posts/myNotes/path2offer/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/实习-nuttx-信号量.md': {
      routes:
        | '/posts/myNotes/path2offer/实习-nuttx-信号量'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/实习-nuttx-aio.md': {
      routes:
        | '/posts/myNotes/path2offer/实习-nuttx-aio'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/bytedance_server_firmware.md': {
      routes:
        | '/posts/myNotes/path2offer/bytedance_server_firmware'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/c_io.md': {
      routes:
        | '/posts/myNotes/path2offer/c_io'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/interview_exp.md': {
      routes:
        | '/posts/myNotes/path2offer/interview_exp'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/linux_kernel.md': {
      routes:
        | '/posts/myNotes/path2offer/linux_kernel'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/mcu.md': {
      routes:
        | '/posts/myNotes/path2offer/mcu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/mcu_ldscript.md': {
      routes:
        | '/posts/myNotes/path2offer/mcu_ldscript'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/mcu_startup.md': {
      routes:
        | '/posts/myNotes/path2offer/mcu_startup'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/path2offer/os_memory.md': {
      routes:
        | '/posts/myNotes/path2offer/os_memory'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/arrival-vector.md': {
      routes:
        | '/posts/myNotes/radar/arrival-vector'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/Capon-algorithm.md': {
      routes:
        | '/posts/myNotes/radar/Capon-algorithm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/Compare_Capon_and_PhaseDiff_algorithm_in_1T2R_Radar.md': {
      routes:
        | '/posts/myNotes/radar/Compare_Capon_and_PhaseDiff_algorithm_in_1T2R_Radar'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/Data_Association-Global_Nearest_Neighbor.md': {
      routes:
        | '/posts/myNotes/radar/Data_Association-Global_Nearest_Neighbor'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/FFT_frequency_interpolation.md': {
      routes:
        | '/posts/myNotes/radar/FFT_frequency_interpolation'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/LFMCW-radar-principle.md': {
      routes:
        | '/posts/myNotes/radar/LFMCW-radar-principle'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/MUSIC-algorithm.md': {
      routes:
        | '/posts/myNotes/radar/MUSIC-algorithm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection.md': {
      routes:
        | '/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation.md': {
      routes:
        | '/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/README.md': {
      routes:
        | '/posts/myNotes/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/resource.md': {
      routes:
        | '/posts/myNotes/resource'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/some-details/compare_numpy_arange_and_linspace.md': {
      routes:
        | '/posts/myNotes/some-details/compare_numpy_arange_and_linspace'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/some-details/gist_url.md': {
      routes:
        | '/posts/myNotes/some-details/gist_url'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/some-details/list_find_in_vscode.md': {
      routes:
        | '/posts/myNotes/some-details/list_find_in_vscode'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/some-details/the-format-of-the-Passtags-of-the-ZMQ-module-in-GNURadio.md': {
      routes:
        | '/posts/myNotes/some-details/the-format-of-the-Passtags-of-the-ZMQ-module-in-GNURadio'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/some-details/transpose-in-matlab.md': {
      routes:
        | '/posts/myNotes/some-details/transpose-in-matlab'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp.md': {
      routes:
        | '/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/tools/Python_scripts_modify_the_encoding_format_of_text_files_in_batches.md': {
      routes:
        | '/posts/myNotes/tools/Python_scripts_modify_the_encoding_format_of_text_files_in_batches'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/zynq/add_lrzsz_in_rootfs.md': {
      routes:
        | '/posts/myNotes/zynq/add_lrzsz_in_rootfs'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/myNotes/zynq/Petalinux_design_process.md': {
      routes:
        | '/posts/myNotes/zynq/Petalinux_design_process'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
