/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/myNotes/mcu/Port-freertos-to-gd32': RouteRecordInfo<'/posts/myNotes/mcu/Port-freertos-to-gd32', '/posts/myNotes/mcu/Port-freertos-to-gd32', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/radar/arrival-vector': RouteRecordInfo<'/posts/myNotes/radar/arrival-vector', '/posts/myNotes/radar/arrival-vector', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/radar/Capon-algorithm': RouteRecordInfo<'/posts/myNotes/radar/Capon-algorithm', '/posts/myNotes/radar/Capon-algorithm', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/radar/LFMCW-radar-principle': RouteRecordInfo<'/posts/myNotes/radar/LFMCW-radar-principle', '/posts/myNotes/radar/LFMCW-radar-principle', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/radar/MUSIC-algorithm': RouteRecordInfo<'/posts/myNotes/radar/MUSIC-algorithm', '/posts/myNotes/radar/MUSIC-algorithm', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection': RouteRecordInfo<'/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection', '/posts/myNotes/radar/Paper-Reading_FMCW_Radar_Heartbeat_detection', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation': RouteRecordInfo<'/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation', '/posts/myNotes/radar/project/doc/1_LFMCW-radar-receiving-signal-simulation', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/README': RouteRecordInfo<'/posts/myNotes/README', '/posts/myNotes/README', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/some-details/repair-linux-grub': RouteRecordInfo<'/posts/myNotes/some-details/repair-linux-grub', '/posts/myNotes/some-details/repair-linux-grub', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/some-details/transpose-in-matlab': RouteRecordInfo<'/posts/myNotes/some-details/transpose-in-matlab', '/posts/myNotes/some-details/transpose-in-matlab', Record<never, never>, Record<never, never>>,
    '/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp': RouteRecordInfo<'/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp', '/posts/myNotes/tools/Convert_images_in_markdown_files_to_webp', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
